version: '3'
services:
  app:
    build:
      context: .
# =========ローカルと本番切り替え===========
  #  command: bundle exec puma -C config/puma.rb -e production
    command: bundle exec puma -C config/puma.rb
# ======================================
    volumes:
      - .:/BestMap
      - public-data:/BestMap/public
      - tmp-data:/BestMap/tmp
      - log-data:/BestMap/log
    networks:
      - BestMap-network
# =========ローカルと本番切り替え===========
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: BestMap_development
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - BestMap-network
# ======================================

  web:
    build:
      context: ./nginx_docker
    volumes:
      - public-data:/BestMap/public
      - tmp-data:/BestMap/tmp
    ports:
      - 80:80
    depends_on:
      - app
    networks:
      - BestMap-network
volumes:
  public-data:

  tmp-data:
  log-data:
  db-data:

networks:
  BestMap-network:
    external: true
